version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: "github.com/fatih/color"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
