version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  ignore:
  - dependency-name: "github.com/fatih/color "
    versions: ">=1.16.0"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
