---
additional:
- anchore-helm
- docker-fpm
- lacework-manifest
- kong-build-tools-base-images
- kong-internal-unstable-helm
- template-github-release

files:
- '!README.md'
- '!.pre-commit-config.yaml'
- '!.secrets.baseline'
- '!**/template-sync.yml'
- '!.github/workflows/sync.yml'
- '!.github/PULL_REQUEST_TEMPLATE.md'
- '!**/CODEOWNERS'
- '!.yamllint'
