version: "2"
linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - exhaustive
    - goconst
    - gomodguard
    - gosec
    - importas
    - lll
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - wastedassign
  settings:
    goconst:
      min-occurrences: 10
    gomodguard:
      blocked:
        modules:
          - github.com/ghodss/yaml:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v2:
              recommendations:
                - sigs.k8s.io/yaml
          - gopkg.in/yaml.v3:
              recommendations:
                - sigs.k8s.io/yaml
          - github.com/pkg/errors:
              recommendations:
                - fmt
                - errors
          - golang.org/x/net/context:
              recommendations:
                - context
    testifylint:
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: state/indexers/md5Indexer.*
        text: weak cryptographic primitive
      - linters:
          - gosec
        path: _test\.go
        text: weak random number generator
      - linters:
          - errcheck
        path: _test\.go
        text: Error return value
      - linters:
          - gosec
        path: file/codegen/main.go
        text: Expect WriteFile permissions to be 0600 or less
      - linters:
          - unparam
          - unused
        path: test_.*
      - linters:
          - staticcheck
        text: SA1019.*
      - linters:
          - staticcheck
        text: "QF1008: could remove embedded field.*"
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
