name: AI Gateway Integration Test
run-name: AI Gateway Integration Test, branch:${{ github.ref_name }}, triggered by @${{ github.actor }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: integration-ai-gateway-${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_call:

jobs:
  integration:
    strategy:
      matrix:
        kong_image:
        - 'kong/kong-ai-gateway-dev:2.0.2-rc.2'
    env:
      KONG_ANONYMOUS_REPORTS: "off"
      KONG_IMAGE: ${{ matrix.kong_image }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{secrets.DOCKER_ORG_NAME}}
          password: ${{secrets.DOCKER_ORG_TOKEN}}
      - uses: Kong/kong-license@bfa1c17600a68d879042f44a9ec3fb5b60f4fad5
        id: license
        with:
          op-token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Kong
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make setup-kong-ee
      - name: Run integration tests
        env:
          KONG_LICENSE_DATA: ${{ steps.license.outputs.license }}
        run: make test-integration
